services:

  mysql:
    image: mysql:8.0
    container_name: phone-store-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: phone_store
    ports:
      - "3307:3306"
    volumes:
      - ./database:/docker-entrypoint-initdb.d